# Generated by Django 3.2.9 on 2021-11-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProgramas',
            fields=[
                ('vp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('video_id', models.IntegerField()),
                ('video_cbarras', models.CharField(max_length=12)),
                ('vp_serie', models.CharField(blank=True, max_length=300, null=True)),
                ('vp_subtitulo', models.CharField(blank=True, max_length=150, null=True)),
                ('vp_sinopsis', models.CharField(blank=True, max_length=1000, null=True)),
                ('vp_participantes', models.CharField(blank=True, max_length=250, null=True)),
                ('vp_personajes', models.CharField(blank=True, max_length=250, null=True)),
                ('vp_areaconocimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('vp_asigmateria', models.CharField(blank=True, max_length=50, null=True)),
                ('vp_niveleducativo', models.CharField(blank=True, max_length=38, null=True)),
                ('vp_grado', models.CharField(blank=True, max_length=40, null=True)),
                ('vp_ejetematico', models.CharField(blank=True, max_length=100, null=True)),
                ('vp_tema', models.CharField(blank=True, max_length=100, null=True)),
                ('vp_institproductora', models.CharField(blank=True, max_length=300, null=True)),
                ('vp_idiomaoriginal', models.CharField(blank=True, max_length=40, null=True)),
                ('vp_elenco', models.CharField(blank=True, max_length=100, null=True)),
                ('vp_conductor', models.CharField(blank=True, max_length=60, null=True)),
                ('vp_locutor', models.CharField(blank=True, max_length=60, null=True)),
                ('vp_guionista', models.CharField(blank=True, max_length=60, null=True)),
                ('vp_investigador', models.CharField(blank=True, max_length=60, null=True)),
                ('vp_derechopatrimonial', models.CharField(blank=True, max_length=60, null=True)),
                ('vp_fechacalificacion', models.DateTimeField(blank=True, null=True)),
                ('vp_calificador', models.CharField(blank=True, max_length=5, null=True)),
                ('vp_fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('vp_calificadormod', models.CharField(blank=True, max_length=5, null=True)),
                ('vp_sistema', models.CharField(blank=True, max_length=4, null=True)),
                ('vp_duracion', models.CharField(blank=True, max_length=10, null=True)),
                ('vp_programa', models.CharField(blank=True, max_length=300, null=True)),
                ('vp_subtitserie', models.TextField(blank=True, null=True)),
                ('vp_orientacion', models.CharField(blank=True, max_length=160, null=True)),
                ('vp_duracionin', models.CharField(blank=True, max_length=165, null=True)),
                ('vp_duracionout', models.CharField(blank=True, max_length=165, null=True)),
                ('vp_duracion1', models.CharField(blank=True, max_length=165, null=True)),
                ('tx', models.CharField(blank=True, max_length=160, null=True)),
                ('vp_observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('vp_fork', models.CharField(blank=True, max_length=300, null=True)),
                ('vp_realizador', models.CharField(blank=True, max_length=600, null=True)),
                ('vp_musicao', models.CharField(blank=True, max_length=600, null=True)),
                ('vp_musicai', models.CharField(blank=True, max_length=600, null=True)),
                ('vp_cantante', models.CharField(blank=True, max_length=600, null=True)),
                ('vp_disquera', models.CharField(blank=True, max_length=600, null=True)),
                ('vp_libreriam', models.CharField(blank=True, max_length=600, null=True)),
                ('vp_registro_obra', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'detalle_programas',
            },
        ),
        migrations.CreateModel(
            name='MaestroCintas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField()),
                ('video_cbarras', models.CharField(max_length=12)),
                ('form_clave', models.IntegerField()),
                ('video_idproduccion', models.IntegerField(blank=True, null=True)),
                ('video_codificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('video_tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('video_fingreso', models.DateTimeField(blank=True, null=True)),
                ('video_inventario', models.CharField(blank=True, max_length=4, null=True)),
                ('video_estatus', models.CharField(max_length=20)),
                ('video_rack', models.CharField(blank=True, max_length=4, null=True)),
                ('video_nivel', models.CharField(blank=True, max_length=4, null=True)),
                ('video_anoproduccion', models.IntegerField(blank=True, null=True)),
                ('video_idproductor', models.IntegerField(blank=True, null=True)),
                ('video_productor', models.CharField(blank=True, max_length=55, null=True)),
                ('video_idcoordinador', models.IntegerField(blank=True, null=True)),
                ('video_coordinador', models.CharField(blank=True, max_length=60, null=True)),
                ('video_usmov', models.IntegerField(blank=True, null=True)),
                ('video_fechamov', models.DateTimeField(blank=True, null=True)),
                ('video_observaciones', models.CharField(blank=True, max_length=238, null=True)),
                ('usua_clave', models.CharField(blank=True, max_length=10, null=True)),
                ('video_fchcal', models.DateTimeField(blank=True, null=True)),
                ('video_target', models.CharField(blank=True, max_length=20, null=True)),
                ('id_tipo', models.IntegerField(blank=True, null=True)),
                ('id_origen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maestro_cintas',
            },
        ),
    ]
