# Generated by Django 4.1.7 on 2023-06-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='pres_fecha_devolucion',
            field=models.DateTimeField(null=True),
        ),
    ]
