# Generated by Django 4.1.7 on 2023-07-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_prestamos_pres_fecha_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocalificacion',
            name='estatusCalif',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
